/**
 * 执镜 · 经典引文库
 * 所有引文均给出篇名出处；「置信度」为针对当下情境匹配程度的主观估计，非科学测量。
 */

export type Tradition = 'zhuangzi' | 'daodejing' | 'sunzi' | 'mao' | 'yinfujing';

export const TRADITION_META: Record<Tradition, { name: string; lens: string; color: string; mirror: string; lensDesc: string }> = {
  zhuangzi: { name: '庄子', lens: '换视角', color: 'text-pine', mirror: '蝶梦签', lensDesc: '这面镜子不评判对错，只把你带到另一个位置，让你看见站在原地看不见的那一面。' },
  daodejing: { name: '道德经', lens: '做减法', color: 'text-gold', mirror: '水镜签', lensDesc: '这面镜子不教你再加什么，只轻声问一句：哪一件，其实可以放下了。' },
  sunzi: { name: '孙子兵法', lens: '评估代价', color: 'text-cinnabar', mirror: '庙算签', lensDesc: '这面镜子不许诺胜利，只逼你在出手之前，把成本、胜率与退路摆到桌面上。' },
  mao: { name: '毛泽东选集', lens: '逼拿事实', color: 'text-cinnabar', mirror: '求是签', lensDesc: '这面镜子不相信感觉，只相信你亲手查到的、亲眼看到的、亲自试过的东西。' },
  yinfujing: { name: '阴符经', lens: '观机深读', color: 'text-pine', mirror: '枢机签', lensDesc: '这面镜子一次只取一句：请你慢慢读，看同一句话如何在自然、做事与习惯三层同时成立——多解并存，正是它的练法。' },
};

export type Theme =
  | 'pressure'     // 压力与焦虑
  | 'choice'       // 选择与纠结
  | 'anger'        // 愤怒与委屈
  | 'relationship' // 人际与冲突
  | 'action'       // 拖延与行动
  | 'gainloss'     // 得失与成败
  | 'meaning'      // 意义与迷茫
  | 'self';        // 自我怀疑

export const THEME_LABELS: Record<Theme, string> = {
  pressure: '压力与焦虑',
  choice: '选择与纠结',
  anger: '愤怒与委屈',
  relationship: '人际与冲突',
  action: '拖延与行动',
  gainloss: '得失与成败',
  meaning: '意义与迷茫',
  self: '自我怀疑',
};

export interface Quote {
  id: string;
  tradition: Tradition;
  text: string;
  source: string;
  themes: Theme[];
  /** 苏格拉底式追问 */
  ask: string;
  /** 一个可执行小实验 */
  experiment: string;
}

export const QUOTES: Quote[] = [
  // ============ 庄子 · 换视角 ============
  {
    id: 'zz-qiushui-jingwa',
    tradition: 'zhuangzi',
    text: '井蛙不可以语于海者，拘于虚也；夏虫不可以语于冰者，笃于时也。',
    source: '《庄子·秋水》',
    themes: ['meaning', 'choice', 'self'],
    ask: '你此刻坚信的这个判断，有多少来自你所在的「井」——你的位置、经历和信息源？换一个位置，它还是事实吗？',
    experiment: '本周找一个与你处境不同的人，请他完整讲一遍对你这件事的看法，你只记录不反驳，圈出三个你从未想到的角度。',
  },
  {
    id: 'zz-qiushui-yu',
    tradition: 'zhuangzi',
    text: '子非鱼，安知鱼之乐？',
    source: '《庄子·秋水》',
    themes: ['relationship', 'anger'],
    ask: '你在推断对方动机时，依据的是证据，还是你自己的感受？如果对方的快乐与委屈你都无法直接知道，你能确认的到底是什么？',
    experiment: '下次与人冲突时，先写下三句话：「我观察到的事实」「我的推测」「我的感受」，分清三者再回应。',
  },
  {
    id: 'zz-xiaoyao-zhiyu',
    tradition: 'zhuangzi',
    text: '且举世誉之而不加劝，举世非之而不加沮。',
    source: '《庄子·逍遥游》',
    themes: ['self', 'pressure', 'gainloss'],
    ask: '你现在的动力里，有多少来自别人的评价？如果全世界既不夸你也不骂你，这件事你还做不做？',
    experiment: '挑一件你只为「别人的眼光」而做的事，这周假装没有任何观众做一次，记录感受的差别。',
  },
  {
    id: 'zz-renjianshi-wuyong',
    tradition: 'zhuangzi',
    text: '人皆知有用之用，而莫知无用之用也。',
    source: '《庄子·人间世》',
    themes: ['meaning', 'pressure', 'gainloss'],
    ask: '你急着证明「有用」的这段时间里，丢掉了什么「无用」的东西？那些无用的东西，曾经给过你什么？',
    experiment: '这周日留出两小时做一件完全「无用」的事（散步、发呆、乱画），事后写下它有没有悄悄改变你对主业的想法。',
  },
  {
    id: 'zz-yangshengzhu-anshi',
    tradition: 'zhuangzi',
    text: '安时而处顺，哀乐不能入也。',
    source: '《庄子·养生主》',
    themes: ['gainloss', 'pressure', 'meaning'],
    ask: '你现在痛苦的这件事里，哪一部分是「时」——时机未到或时机已过，不以你的意志为转移？把它和「你能做的部分」分开。',
    experiment: '把困扰你的事写成两列清单：「时」（不可控）与「顺」（可顺势而做）。未来一周只处理右列，左列每天只看一眼。',
  },
  {
    id: 'zz-xiaoyao-jiaoliao',
    tradition: 'zhuangzi',
    text: '鹪鹩巢于深林，不过一枝；偃鼠饮河，不过满腹。',
    source: '《庄子·逍遥游》',
    themes: ['pressure', 'gainloss', 'choice'],
    ask: '你想要的总量里，多少是「一枝」「满腹」的真实需要，多少是整条大河般的焦虑性囤积？',
    experiment: '写下你当前目标对应的「最小够用版本」，标注：达成最小版之后，剩下的部分是想要还是需要？',
  },
  {
    id: 'zz-renjianshi-xushi',
    tradition: 'zhuangzi',
    text: '虚室生白，吉祥止止。',
    source: '《庄子·人间世》',
    themes: ['pressure', 'meaning'],
    ask: '你的脑子最近是不是塞得太满了？如果清空一角，什么东西会自己浮现出来？',
    experiment: '明天起床后先做 15 分钟「空室练习」：不看手机，只是坐着，让想法自己冒出来，把第一个反复出现的想法记下来。',
  },
  {
    id: 'zz-renjianshi-naihe',
    tradition: 'zhuangzi',
    text: '知其不可奈何而安之若命，德之至也。',
    source: '《庄子·人间世》',
    themes: ['gainloss', 'meaning', 'pressure'],
    ask: '区分一下：这件事里什么是「不可奈何」（真的改不了），什么是你还没试过的？庄子的「安」，只针对前者。',
    experiment: '选一件你认定「没办法」的事，列出三条你从未试过的路径，哪怕看起来笨拙，本周试其中一条。',
  },

  // ============ 道德经 · 做减法 ============
  {
    id: 'ddj-48',
    tradition: 'daodejing',
    text: '为学日益，为道日损。损之又损，以至于无为。',
    source: '《道德经》第四十八章',
    themes: ['pressure', 'choice', 'meaning'],
    ask: '你现在的问题，是「知道的还不够」，还是「背着的太多」？如果答案是后者，第一个该扔掉的是什么？',
    experiment: '列出你正在同时推进的所有事项，按「不做会怎样」排序，本周正式停掉排在最后的两项，并告知相关的人。',
  },
  {
    id: 'ddj-22-shao',
    tradition: 'daodejing',
    text: '少则得，多则惑。',
    source: '《道德经》第二十二章',
    themes: ['choice', 'pressure', 'action'],
    ask: '你纠结的选项里，是不是有几个其实只是「看起来不甘心放弃」？只留一个，你会留哪个？为什么？',
    experiment: '把当前纠结的选项全部写下，划到只剩一个。把被划掉的选项各写一句「放弃它的代价」，看哪个代价其实最小。',
  },
  {
    id: 'ddj-44-zhizu',
    tradition: 'daodejing',
    text: '知足不辱，知止不殆，可以长久。',
    source: '《道德经》第四十四章',
    themes: ['gainloss', 'pressure'],
    ask: '这条赛道上，「止」线在哪里——达到什么状态你就可以停下来享受，而不是继续加码？你定义过这条线吗？',
    experiment: '为你当前最用力的一件事写一条「止线」（具体的、可观察的状态），把它贴在看得见的地方，一周后回看你是否越过了它。',
  },
  {
    id: 'ddj-58-huofu',
    tradition: 'daodejing',
    text: '祸兮福之所倚，福兮祸之所伏。',
    source: '《道德经》第五十八章',
    themes: ['gainloss', 'meaning'],
    ask: '这件「坏事」里藏着什么资源（时间、教训、新关系）？那件「好事」里又埋着什么代价？',
    experiment: '取最近一好一坏两件事，各写三条「反向清单」：坏事带来的三个意外收获，好事附带的三个隐患。',
  },
  {
    id: 'ddj-63-nanshi',
    tradition: 'daodejing',
    text: '天下难事，必作于易；天下大事，必作于细。',
    source: '《道德经》第六十三章',
    themes: ['action', 'pressure', 'self'],
    ask: '这件「难事」最容易的那个切口是什么？小到不可能失败的第一步，长什么样？',
    experiment: '把目标切成一个「两分钟版本」今天执行（写两行字、发一条消息、打开一个文档），只要求自己做到最小版。',
  },
  {
    id: 'ddj-24-qizhe',
    tradition: 'daodejing',
    text: '企者不立，跨者不行。',
    source: '《道德经》第二十四章',
    themes: ['action', 'gainloss', 'self'],
    ask: '踮脚站不稳，跨步走不远——你现在的计划里，哪一步是在「踮脚」：靠透支、靠运气、靠别人配合才能成立？',
    experiment: '检查你本周计划，找出最依赖「超常发挥」的一环，把它改成「正常发挥也能完成」的版本。',
  },
  {
    id: 'ddj-33-zhiren',
    tradition: 'daodejing',
    text: '知人者智，自知者明。胜人者有力，自胜者强。',
    source: '《道德经》第三十三章',
    themes: ['self', 'relationship'],
    ask: '你对那个人的判断很清晰——那你自己在这件事里的角色呢？用同样清晰的话说一遍。',
    experiment: '用你评价对方的同一套标准，给自己写一段「第三方评价」，不辩护、不美化，写完对比两段的措辞差异。',
  },
  {
    id: 'ddj-8-shuishan',
    tradition: 'daodejing',
    text: '上善若水。水善利万物而不争，处众人之所恶，故几于道。',
    source: '《道德经》第八章',
    themes: ['relationship', 'anger', 'meaning'],
    ask: '这场冲突里，「争」赢了你能得到什么？如果像水一样先流向低处、绕开正面，三周后局面会变成什么样？',
    experiment: '选一处你正在僵持的争执，本周主动做一次「不争」的让步（无关原则的），观察对方的反应与你自己的损失。',
  },

  // ============ 孙子兵法 · 评估代价 ============
  {
    id: 'sz-jipian-duosuan',
    tradition: 'sunzi',
    text: '夫未战而庙算胜者，得算多也；未战而庙算不胜者，得算少也。多算胜，少算不胜，而况于无算乎！',
    source: '《孙子兵法·计篇》',
    themes: ['choice', 'action', 'gainloss'],
    ask: '动手之前你「算」过吗：成本、胜率、退路各是什么？如果答案是没算，你是在做决定还是在掷骰子？',
    experiment: '为你纠结的事画一张「庙算表」：投入（钱/时间/关系）、最好结果、最坏结果、退路。四项都填不出具体数字的部分，就是你要先去侦察的地方。',
  },
  {
    id: 'sz-mougong-zhizhi',
    tradition: 'sunzi',
    text: '知彼知己，百战不殆。',
    source: '《孙子兵法·谋攻篇》',
    themes: ['choice', 'relationship', 'self'],
    ask: '你对「彼」（对手、环境、市场、对方）的了解，有多少是一手信息？对「己」的盘点，有没有水分？',
    experiment: '本周补一次「知彼」功课：找三个真正处于「彼」位置的人聊，或读三份一手材料，修正你的判断后再决定。',
  },
  {
    id: 'sz-xingpian-xianwei',
    tradition: 'sunzi',
    text: '昔之善战者，先为不可胜，以待敌之可胜。',
    source: '《孙子兵法·形篇》',
    themes: ['action', 'gainloss', 'pressure'],
    ask: '你现在是在「求胜」，还是先「立于不败」？如果最坏情况明天就发生，你扛得住吗？',
    experiment: '写下你的「不可胜清单」：现金流能撑几个月、技能离开平台还值多少、关系里谁一定接你电话。薄弱项选一个，本周加固。',
  },
  {
    id: 'sz-jiudi-heli',
    tradition: 'sunzi',
    text: '合于利而动，不合于利而止。',
    source: '《孙子兵法·九地篇》',
    themes: ['anger', 'choice', 'relationship'],
    ask: '你现在想做的这个反击／决定，是「合于利」还是「合于气」？情绪退掉之后，利还在吗？',
    experiment: '把想发的火、想做的决定先写下来放进抽屉，48 小时后重读，问自己：这条行动的收益表变了吗？没变再执行。',
  },
  {
    id: 'sz-huogong-zhu',
    tradition: 'sunzi',
    text: '主不可以怒而兴师，将不可以愠而致战。',
    source: '《孙子兵法·火攻篇》',
    themes: ['anger', 'relationship'],
    ask: '怒可以复息，愠可以复悦，但亡国不可以复存、死者不可以复生——你这一仗打出去，有没有不可逆的东西在里面？',
    experiment: '列出这场冲突中「不可逆清单」（说了收不回的话、删了找不回的数据、伤了难修复的关系），凡在清单上的动作，一律先冷却 72 小时。',
  },
  {
    id: 'sz-jiudi-wangdi',
    tradition: 'sunzi',
    text: '投之亡地然后存，陷之死地然后生。',
    source: '《孙子兵法·九地篇》',
    themes: ['action', 'self', 'meaning'],
    ask: '你是一直在等「更安全」的时机，还是其实已经把自己放进了「不行动才最危险」的境地？',
    experiment: '定义你的「死地」：再拖三个月，具体会失去什么？把这个损失写清楚贴在桌前，比打鸡血有效。',
  },

  // ============ 毛泽东选集 · 逼拿事实 ============
  {
    id: 'mao-benben-diaocha',
    tradition: 'mao',
    text: '没有调查，就没有发言权。',
    source: '《反对本本主义》（1930 年 5 月）',
    themes: ['choice', 'relationship', 'gainloss'],
    ask: '你这个判断背后，有几条是你亲自调查来的事实？有几条是听来的、刷到的、想象的？比例是多少？',
    experiment: '把你的结论写在纸上方，下方列「事实栏」：只写你亲眼所见、亲耳所闻、亲手查到的。填不满五行，就先去做调查再谈决定。',
  },
  {
    id: 'mao-shijian-shili',
    tradition: 'mao',
    text: '你要知道梨子的滋味，你就得变革梨子，亲口吃一吃。',
    source: '《实践论》（1937 年 7 月）',
    themes: ['action', 'choice', 'self'],
    ask: '关于这件事，你已经「研究」多久了？有没有一种成本可承受的方式，直接「咬一口」试试？',
    experiment: '设计一个 7 天内的「最小实践」：兼职体验一天、约行业内的人聊一小时、做一个样品出来。用嘴尝，不用脑补。',
  },
  {
    id: 'mao-shijian-zhenli',
    tradition: 'mao',
    text: '马克思主义者认为，只有人们的社会实践，才是人们对于外界认识的真理性的标准。',
    source: '《实践论》（1937 年 7 月）',
    themes: ['self', 'meaning', 'gainloss'],
    ask: '你说「我不行」「这事成不了」——这个认识的检验标准是什么？你拿实践验过它，还是拿想象供着它？',
    experiment: '挑一个你长期相信的自我判断（如「我不擅长表达」），设计一次公开的小实践去检验它，让结果而不是想象说话。',
  },
  {
    id: 'mao-maodun-zhuyao',
    tradition: 'mao',
    text: '捉住了这个主要矛盾，一切问题就迎刃而解了。',
    source: '《矛盾论》（1937 年 8 月）',
    themes: ['pressure', 'choice', 'meaning'],
    ask: '你面临的十个问题里，哪一个是「主要矛盾」——它一解决，其他九个会跟着松动？你现在 80% 的精力花在哪一个上？',
    experiment: '列出所有困扰，两两比较「解决 A 会不会顺带缓解 B」，找出被缓解次数最多的那个，下周把最好的时段只给它。',
  },
  {
    id: 'mao-gaizao-shishi',
    tradition: 'mao',
    text: '「实事」就是客观存在着的一切事物，「是」就是客观事物的内部联系，即规律性，「求」就是我们去研究。',
    source: '《改造我们的学习》（1941 年 5 月）',
    themes: ['meaning', 'self', 'choice'],
    ask: '你是在「求」（研究事实与规律），还是在「许愿」（重复愿望和情绪）？这两种状态在一天里各占几小时？',
    experiment: '连续三天记录时间开销：标注每一小时属于「求是」（获取事实、验证假设）还是「许愿」（焦虑、空想、抱怨）。第四天调整比例。',
  },
  {
    id: 'mao-zhanlue-mieshi',
    tradition: 'mao',
    text: '在战略上藐视敌人，在战术上重视敌人。',
    source: '《关于目前党的政策中的几个重要问题》（1948 年 1 月）',
    themes: ['self', 'pressure', 'action'],
    ask: '你对这件事的态度是不是反过来了——战略上被吓住（「我不可能做到」），战术上又很轻视（从不拆解步骤）？',
    experiment: '写两段话：第一段用最大胆的战略口吻说「这事本质上没什么了不起」；第二段用最务实的战术口吻列出全部细节步骤。两段都写完才算数。',
  },
  // ============ 庄子 · 换视角（扩） ============
  {
    id: 'zz-qiwu-mengdie',
    tradition: 'zhuangzi',
    text: '昔者庄周梦为胡蝶，栩栩然胡蝶也。不知周之梦为胡蝶与，胡蝶之梦为周与？',
    source: '《庄子·齐物论》',
    themes: ['meaning', 'self'],
    ask: '你现在认定「这就是现实」的这件事，有没有可能只是你正在做的一场梦——一种暂时还没醒的解释？',
    experiment: '把最困扰你的事用「如果三年后回看」的视角写一段话，再写一段「如果我是旁观者」的版本，对比哪段更接近事实。',
  },
  {
    id: 'zz-dazongshi-xiangru',
    tradition: 'zhuangzi',
    text: '泉涸，鱼相与处于陆，相呴以湿，相濡以沫，不如相忘于江湖。',
    source: '《庄子·大宗师》',
    themes: ['relationship', 'gainloss'],
    ask: '这段关系里，你们是在互相滋养，还是只是在干涸里互相消耗？「相忘于江湖」对你们各自意味着什么？',
    experiment: '写下这段关系给你的三样东西和拿走的三样东西。如果拿走的大于给予的，本周先把自己的「江湖」找回来：一件独处也能让你恢复的事。',
  },
  {
    id: 'zz-yangsheng-youya',
    tradition: 'zhuangzi',
    text: '吾生也有涯，而知也无涯。以有涯随无涯，殆已！',
    source: '《庄子·养生主》',
    themes: ['pressure', 'choice'],
    ask: '你想学完、看完、准备好的清单，是永远拉不完的——你到底在等哪个「足够了」的信号？谁规定的？',
    experiment: '给你正在追的学习／信息清单设一个「涯」：本周只保留三个来源，其余全部取关，观察焦虑是升还是降。',
  },
  {
    id: 'zz-xiaoyao-jishui',
    tradition: 'zhuangzi',
    text: '且夫水之积也不厚，则其负大舟也无力。',
    source: '《庄子·逍遥游》',
    themes: ['action', 'self'],
    ask: '你想负的那条「大舟」，现在下面有多少「水」？你缺的到底是船，还是还没来得及积的水？',
    experiment: '把目标需要的「水」拆成可积累的单位（作品数、客户数、练习时长），写下你现在的水位线，只定下周的蓄水目标。',
  },
  {
    id: 'zz-tianzifang-xinsi',
    tradition: 'zhuangzi',
    text: '哀莫大于心死，而人死亦次之。',
    source: '《庄子·田子方》',
    themes: ['meaning', 'pressure'],
    ask: '你现在对什么事还「心动」？如果答案是很难想，问题可能不在你做的事上，而在你和事的关系上。',
    experiment: '本周每天记一笔「心动时刻」：哪怕只是喝到一杯好茶。周末回看，你的心到底对什么还活着？',
  },
  {
    id: 'zz-shanmu-danshui',
    tradition: 'zhuangzi',
    text: '君子之交淡若水，小人之交甘若醴。',
    source: '《庄子·山木》',
    themes: ['relationship'],
    ask: '你现在的关系里，哪些是「甘若醴」——靠甜头和热度维持的？热度退掉后还剩什么？',
    experiment: '挑一段你想长久的关系，这周做一次「淡」的互动：不请客、不帮忙、不迎合，只真诚地聊一次近况。',
  },
  {
    id: 'zz-qiwu-tiandi',
    tradition: 'zhuangzi',
    text: '天地与我并生，而万物与我为一。',
    source: '《庄子·齐物论》',
    themes: ['meaning', 'pressure'],
    ask: '你把自己和「万物」对立太久了——你的失败、你的落后，放在天地的尺度上，真的有那么重吗？',
    experiment: '今晚出门走二十分钟，刻意看天、看树、看路人，不看手机。回来后用三句话写下尺度变化后的感受。',
  },
  {
    id: 'zz-lieyukou-wuqiu',
    tradition: 'zhuangzi',
    text: '巧者劳而知者忧，无能者无所求。',
    source: '《庄子·列御寇》',
    themes: ['pressure', 'gainloss'],
    ask: '你的「巧」和「知」给你带来了劳与忧——它们在替你换什么？这笔交换你还愿意继续吗？',
    experiment: '列出你因为「能干」而接下的所有额外负担，本周挑一件正式还回去，观察天有没有塌。',
  },

  // ============ 道德经 · 做减法（扩） ============
  {
    id: 'ddj-64-qianli',
    tradition: 'daodejing',
    text: '千里之行，始于足下。',
    source: '《道德经》第六十四章',
    themes: ['action', 'self'],
    ask: '你等的「正式开始」到底是什么？脚下这一步小到不起眼的动作，为什么偏偏今天不能做？',
    experiment: '现在就做这件事的「五分钟版本」，做完在本子上记下日期。这张记录比任何计划都值钱。',
  },
  {
    id: 'ddj-64-shenzhong',
    tradition: 'daodejing',
    text: '慎终如始，则无败事。',
    source: '《道德经》第六十四章',
    themes: ['action', 'gainloss'],
    ask: '你的计划通常在第几周开始松掉？如果结尾要像开头一样认真，你现在该提前布置什么？',
    experiment: '给你正在做的事设一个「终点仪式」：定义完成的标准和日期，提前告诉一个人，让他到时候来验收。',
  },
  {
    id: 'ddj-23-piaofeng',
    tradition: 'daodejing',
    text: '飘风不终朝，骤雨不终日。',
    source: '《道德经》第二十三章',
    themes: ['pressure', 'gainloss'],
    ask: '你此刻的这场「骤雨」，按规律它能下多久？你需要的到底是雨伞，还是只是知道它会停？',
    experiment: '写下你认为「永远好不了」的事，标注开始时间，然后设一个两周后的提醒，到时候回来看雨停了没有。',
  },
  {
    id: 'ddj-45-dacheng',
    tradition: 'daodejing',
    text: '大成若缺，其用不弊。大盈若冲，其用不穷。',
    source: '《道德经》第四十五章',
    themes: ['self', 'gainloss'],
    ask: '你拼命掩饰的那个「缺」，会不会正是你还能继续装东西的地方？真正的满，是再也装不下新东西。',
    experiment: '写下你最想藏起来的一个短板，然后写三条「正因为有这个短板，我才……」的句子。',
  },
  {
    id: 'ddj-26-jingzao',
    tradition: 'daodejing',
    text: '重为轻根，静为躁君。',
    source: '《道德经》第二十六章',
    themes: ['pressure', 'anger'],
    ask: '你最近的「躁」——急着回复、急着表态、急着翻盘——是因为哪件「重」的事被你丢掉了？',
    experiment: '下次情绪上头时，先做一个「重」的动作：喝水、走路十分钟、写三行字，再决定动不动。',
  },
  {
    id: 'ddj-22-buzheng',
    tradition: 'daodejing',
    text: '夫唯不争，故天下莫能与之争。',
    source: '《道德经》第二十二章',
    themes: ['relationship', 'gainloss'],
    ask: '你正在争的这个东西，争到手要付多少成本？如果换一条没人争的赛道，你的赢面反而多大？',
    experiment: '列出你所在赛道上人人挤破头争夺的三个资源，再写出三条没人注意但你够得着的「不争之路」，本周探一条。',
  },
  {
    id: 'ddj-66-jianghai',
    tradition: 'daodejing',
    text: '江海所以能为百谷王者，以其善下之。',
    source: '《道德经》第六十六章',
    themes: ['relationship', 'meaning'],
    ask: '在这件事上「居下」——先听、先认、先服务——你会失去什么实际的东西，还是会换来百川归海？',
    experiment: '本周在一次分歧中第一个说「你先说，我听着」，全程不反驳，事后记录你多知道了什么。',
  },
  {
    id: 'ddj-81-xinyan',
    tradition: 'daodejing',
    text: '信言不美，美言不信。',
    source: '《道德经》第八十一章',
    themes: ['relationship', 'self'],
    ask: '最近让你最舒服的那句话，经得起查吗？让你最不舒服的那句逆耳之言，有没有可能是真的？',
    experiment: '找一位敢说真话的人，请他指出你最近一个决定里最可疑的地方，只听不辩，写下来过夜再回应。',
  },

  // ============ 孙子兵法 · 评估代价（扩） ============
  {
    id: 'sz-xing-xiansheng',
    tradition: 'sunzi',
    text: '胜兵先胜而后求战，败兵先战而后求胜。',
    source: '《孙子兵法·形篇》',
    themes: ['action', 'choice'],
    ask: '你是先把胜算做足再出手，还是已经冲出去、指望在路上捡到胜算？',
    experiment: '写下你准备做的这件事的「先胜清单」：哪三个条件齐了才算有胜算？没齐之前，本周只补条件不开战。',
  },
  {
    id: 'sz-shi-qiushi',
    tradition: 'sunzi',
    text: '故善战者，求之于势，不责于人。',
    source: '《孙子兵法·势篇》',
    themes: ['pressure', 'self'],
    ask: '你最近在怪谁——怪团队、怪伴侣、怪自己？如果把力气改去调「势」（环境、时机、结构），第一块要动的石头是什么？',
    experiment: '把你归咎于人的三条抱怨，各改写成一条「势」的调整方案（换时间、换顺序、换规则），本周执行一条。',
  },
  {
    id: 'sz-junzheng-duoxin',
    tradition: 'sunzi',
    text: '三军可夺气，将军可夺心。',
    source: '《孙子兵法·军争篇》',
    themes: ['anger', 'pressure'],
    ask: '对方最近是不是正在「夺你的心」——让你慌、让你怒、让你乱？你一旦乱了，输的是哪一局？',
    experiment: '识别出那个专门扰乱你节奏的触发源（一个人、一个群、一个推送），本周对它做一次物理隔离，记录心稳了多少。',
  },
  {
    id: 'sz-jiubian-tusuoyou',
    tradition: 'sunzi',
    text: '途有所不由，军有所不击，城有所不攻，地有所不争。',
    source: '《孙子兵法·九变篇》',
    themes: ['choice', 'gainloss'],
    ask: '你的版图里，哪几座「城」其实根本不必攻？不攻它们，省下的兵力够你拿下什么真正要的东西？',
    experiment: '写下你正在打的四场「仗」，强制指定其中一场为「不攻之城」，本周零投入，把省下的时间投给最重要那场。',
  },
  {
    id: 'sz-jiubian-lihai',
    tradition: 'sunzi',
    text: '是故智者之虑，必杂于利害。',
    source: '《孙子兵法·九变篇》',
    themes: ['choice', 'gainloss'],
    ask: '利中你看到害了吗，害中你看到利了吗？只算一边的账，是你现在犹豫不决的真正原因吗？',
    experiment: '为你纠结的事画四格：做之利、做之害、不做之利、不做之害。填满再决定，缺的那格往往就是答案。',
  },
  {
    id: 'sz-jiubian-wushi',
    tradition: 'sunzi',
    text: '无恃其不来，恃吾有以待也。',
    source: '《孙子兵法·九变篇》',
    themes: ['pressure', 'action'],
    ask: '你是在赌「坏事不会发生」，还是已经备好「来了我也有办法」？赌注和准备，哪个更让你睡得着？',
    experiment: '为你最担心的一个风险写一份「有以待」预案：触发信号是什么、第一步做什么、找谁帮忙。写完存好。',
  },
  {
    id: 'sz-mougong-zhizhan',
    tradition: 'sunzi',
    text: '知可以战与不可以战者胜。',
    source: '《孙子兵法·谋攻篇》',
    themes: ['choice', 'anger'],
    ask: '这一仗属于「可以战」还是「不可以战」？你判断的标尺是形势，还是面子？',
    experiment: '给你想迎战的这件事设三条「开战门槛」（成本上限、胜算下限、退路），三条不齐，一律不应战。',
  },
  {
    id: 'sz-zuozhan-buguijiu',
    tradition: 'sunzi',
    text: '兵贵胜，不贵久。',
    source: '《孙子兵法·作战篇》',
    themes: ['action', 'gainloss'],
    ask: '这件事你打算「久」到什么时候？拖着的每一天在消耗什么？速战速决的版本长什么样？',
    experiment: '给拖了最久的那件事设一个「决战周」：七天内要么拿下、要么认输放弃，不许进入第八天。',
  },

  // ============ 毛泽东选集 · 逼拿事实（扩） ============
  {
    id: 'mao-xingxing-liaoyuan',
    tradition: 'mao',
    text: '星星之火，可以燎原。',
    source: '《星星之火，可以燎原》（1930 年 1 月）',
    themes: ['meaning', 'self', 'pressure'],
    ask: '你手里那点看似微不足道的「星火」——一个小客户、一篇小作品、一个小习惯——给它足够时间，能燎原成什么？',
    experiment: '找出你最小但还活着的那个「火种」，本周给它每天三十分钟的固定氧气，三十天后再评估。',
  },
  {
    id: 'mao-chongqing-quzhe',
    tradition: 'mao',
    text: '前途是光明的，道路是曲折的。',
    source: '《关于重庆谈判》（1945 年 10 月）',
    themes: ['pressure', 'meaning'],
    ask: '你是不是把「道路曲折」误读成了「前途无望」？曲折是路线问题，无望是结论问题——你手上证据支持哪个？',
    experiment: '画一条你这件事的真实进度曲线（别画直线），标出三个已经跨过去的弯，再看看现在这个弯有多特别。',
  },
  {
    id: 'mao-wenyuan-wugu',
    tradition: 'mao',
    text: '世界上没有无缘无故的爱，也没有无缘无故的恨。',
    source: '《在延安文艺座谈会上的讲话》（1942 年 5 月）',
    themes: ['relationship', 'anger'],
    ask: '那个人对你的态度让你想不通——「缘」和「故」你去找过吗，还是只停留在「他就是这样的人」？',
    experiment: '选一段让你困惑的关系，列出对方立场里三个可能的「缘故」（利益、处境、经历），找一条可验证的，去核实。',
  },
  {
    id: 'mao-bada-qianxu',
    tradition: 'mao',
    text: '虚心使人进步，骄傲使人落后。',
    source: '《中国共产党第八次全国代表大会开幕词》（1956 年 9 月）',
    themes: ['self', 'gainloss'],
    ask: '最近一次你笃定「我懂了」的领域，有没有新证据被你挡在门外？骄傲最先关闭的是哪个信息通道？',
    experiment: '本周主动找一条「证明我错了」的证据：搜对立观点、问反方的人。找不到，才说明你真的懂。',
  },
  {
    id: 'mao-minzu-manzu',
    tradition: 'mao',
    text: '学习的敌人是自己的满足。',
    source: '《中国共产党在民族战争中的地位》（1938 年 10 月）',
    themes: ['self', 'meaning'],
    ask: '你在哪个领域已经「满足」到不再学习了？那个领域正在发生的变化，你还看得见吗？',
    experiment: '选一个你自认熟练的技能，本周找一位做得比你好的人，拆解他的三个做法，挑一个偷过来。',
  },
  {
    id: 'mao-xingshi-mingyun',
    tradition: 'mao',
    text: '我们自己的命运完全应当由我们自己来掌握。',
    source: '《目前形势和我们的任务》（1947 年 12 月）',
    themes: ['self', 'meaning', 'action'],
    ask: '这件事你正在等谁批准、等谁拯救、等谁改变？如果批准你的人永远不来，你自己掌握的那部分是什么？',
    experiment: '把「等别人」清单改写为「自己掌握」清单：每一项注明不靠任何人你今天就能做的那一步，明天先做一项。',
  },
  {
    id: 'mao-xuanchuan-xuexi',
    tradition: 'mao',
    text: '情况是在不断地变化，要使自己的思想适应新的情况，就得学习。',
    source: '《在中国共产党全国宣传工作会议上的讲话》（1957 年 3 月）',
    themes: ['meaning', 'action', 'gainloss'],
    ask: '你现在用的打法，是哪一年的「情况」教你的？情况已经变了几轮，你的思想更新过没有？',
    experiment: '写下你赖以生存的三条旧经验，逐条问「现在还成立吗」，找一条失效的，本周换成新打法试验。',
  },
  {
    id: 'mao-sunzhongshan-xiangqian',
    tradition: 'mao',
    text: '我们总要努力，我们总要拼命向前。',
    source: '《纪念孙中山先生》（1956 年 11 月）',
    themes: ['action', 'meaning', 'self'],
    ask: '「向前」对你来说此刻具体是什么动作？不是口号，是今天下班前能做到的那一下。',
    experiment: '把「努力」翻译成今天的三个具体动作（几点到几点、做什么、产出什么），做完打一个勾再睡。',
  },

  // ============ 阴符经 · 观机深读（短章细读，多解并存） ============
  {
    id: 'yfj-guantian',
    tradition: 'yinfujing',
    text: '观天之道，执天之行，尽矣。',
    source: '《阴符经·上篇》',
    themes: ['action', 'meaning', 'choice'],
    ask: '你推进这件事靠的是自己的蛮劲，还是事物本身的节律？它的「天之行」——不以你意志为转移的节拍——你观察过几天？',
    experiment: '选一件你天天做的事，先花三天只观察不干预：什么时辰最顺、哪个环节最卡。第四天顺着节律只调整一个动作，记录差别。',
  },
  {
    id: 'yfj-wuzei',
    tradition: 'yinfujing',
    text: '天有五贼，见之者昌。',
    source: '《阴符经·上篇》',
    themes: ['choice', 'gainloss', 'meaning'],
    ask: '「五贼」历代注家说法不一（命、物、时、功、神；或五行）——这正是练习：驱动你这件事的隐形变量有哪几个？你真正看见的有几个？',
    experiment: '写下影响当前这件事的五个变量，标注哪几个你从未认真看过。本周盯住最陌生的那一个，每天记一笔它的变化。',
  },
  {
    id: 'yfj-yuzhou',
    tradition: 'yinfujing',
    text: '宇宙在乎手，万化生乎身。',
    source: '《阴符经·上篇》',
    themes: ['self', 'action'],
    ask: '你把多少改变的可能推给了「环境」？剥到最后一层，你手里实际能握住的是哪一部分？',
    experiment: '列出你的「我改变不了」清单，逐条追问「其中 5% 我能动的部分是什么」，挑一条今天就动，做完记录。',
  },
  {
    id: 'yfj-qiaozhuo',
    tradition: 'yinfujing',
    text: '性有巧拙，可以伏藏。',
    source: '《阴符经·中篇》',
    themes: ['self', 'choice', 'relationship'],
    ask: '你的「巧」用在什么地方其实是露怯，你的「拙」藏在什么地方反而是底气？伏与藏，都是主动的选择。',
    experiment: '写下你最引以为傲和最自卑的各一点，本周互换一次：巧处藏一藏（不抢话、不炫技），拙处亮一亮（承认不懂、当众请教），记录反馈。',
  },
  {
    id: 'yfj-jizaimu',
    tradition: 'yinfujing',
    text: '心生于物，死于物，机在目。',
    source: '《阴符经·下篇》',
    themes: ['pressure', 'self', 'action'],
    ask: '你的心最近被什么「物」牵着走？它每天从你眼睛里进来多少次——屏幕、推送、别人的生活？「机在目」，入口在你手里。',
    experiment: '记录一天里所有让你心神一动的「入口」，给最大的那个设一道闸（关推送、移出首屏、换位置），观察三天心稳了多少。',
  },
  {
    id: 'yfj-riyueyoushu',
    tradition: 'yinfujing',
    text: '日月有数，大小有定，圣功生焉，神明出焉。',
    source: '《阴符经·下篇》',
    themes: ['action', 'gainloss', 'self'],
    ask: '你想要「大成」，可你为「有数」的日积月累留了多少定课？没有定数的努力，只是随机波动。',
    experiment: '定一个每天雷打不动的「数」（如三十分钟、五百字、二十个客户），写进日程当约会对待。先守二十一天，再谈结果。',
  },
];
